version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    working_dir: /usr/src/app
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: activejobtest